#!/bin/bash

TOP="../../.."
DIR="${TOP}/tests/fft_ext"
TESTS="$(cd ${DIR} && ls -1 -- *.cpp)"

INSTALL_DIR="/opt/homebrew"
CPP="c++"
CPPFLAGS="-I${TOP}/tests -I${TOP}/support -I${INSTALL_DIR}/include"
LDFLAGS="-L${INSTALL_DIR}/lib -lovxx -framework Accelerate"


function build()
{
    local exec="${1}"
    local file="${exec}.cpp"
    if [[ ! -x "${exec}" || "${file}" -nt "${exec}" ]]; then
        "${CPP}" -o "${exec}" ${CPPFLAGS} ${LDFLAGS} "${DIR}/${file}" > "${file}.log" 2>&1
        status=$?
        if [[ "${status}" = "0" ]]; then
            echo "compile ${file} - OK"
        else
            echo "compile ${file} - FAILED (see ${file}.log)"
            rm -f "${exec}"
        fi
    fi
    return ${status}
}

function run()
{
    local exec="${1}"
    local arg="${2}"
    DYLD_LIBRARY_PATH=${INSTALL_DIR}/lib "./${exec}" "${arg}" > "${exec}-${arg##*/}.log" 2>&1
    status=$?
    if [[ "${status}" = "0" ]]; then
        echo "run ${exec} ${arg} - OK"
    else
        echo "run ${exec} ${arg} - FAILED (see ${exec}-${arg##*/}.log)"
    fi
    return ${status}
}

for file in ${TESTS}; do
    exec="${file%.cpp}"
    build "${exec}"
    status=$?
    if [[ "${status}" = "0" ]]; then
        for data in ${DIR}/data/*; do
            run "${exec}" "${data}"
        done
    fi
done
